//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        public int IdEvenement { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ParcelleId { get; set; }
        public int EvenementParcelleId { get; set; }
    
        public virtual EvenementParcelle EvenementParcelle { get; set; }
        public virtual Parcelle Parcelle { get; set; }
    }
}
