//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcelle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parcelle()
        {
            this.Evenements = new HashSet<Evenement>();
        }
    
        public int IdParcelle { get; set; }
        public string Nom { get; set; }
        public string Ville { get; set; }
        public string Adresse { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evenement> Evenements { get; set; }
    }
}
